<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Katalon Studio</name>
   <tag></tag>
   <elementGuidId>72550930-9d94-468d-8aa1-f6585e2d10fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='firstHeading']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.mw-page-title-main</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bfe0eb2f-359d-4bd5-be14-07d0b9acdf46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mw-page-title-main</value>
      <webElementGuid>fe6f8449-4733-4d25-af9c-39bd307f54e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon Studio</value>
      <webElementGuid>114049ff-e24c-498f-b257-9b04732345b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;firstHeading&quot;)/span[@class=&quot;mw-page-title-main&quot;]</value>
      <webElementGuid>f50ad440-65a0-4966-903c-e47bb10e73d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h1[@id='firstHeading']/span</value>
      <webElementGuid>d35ce169-a45e-4144-a79e-8e96afb9edc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đóng mở mục lục'])[2]/following::span[1]</value>
      <webElementGuid>33a13c64-8b38-45ad-97d9-2dd1c0888577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đóng mở mục lục'])[1]/following::span[3]</value>
      <webElementGuid>2d828015-01e0-4efe-85c2-ca3094d61eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/preceding::span[3]</value>
      <webElementGuid>1de87876-eeeb-44e8-a344-326099750120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bài viết'])[1]/preceding::span[5]</value>
      <webElementGuid>d80a94de-104f-4022-85f4-ff5808daf2a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Katalon Studio']/parent::*</value>
      <webElementGuid>012cca7d-2e69-46c5-b590-2abae594b29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>61f7eeb3-a944-4a6e-be24-90996f045065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Katalon Studio' or . = 'Katalon Studio')]</value>
      <webElementGuid>cac87a71-db3a-4b4d-982d-4cd4a72e075e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
