<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>wiki-progress</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ae91eaef-31cf-4fa9-bb14-145d98877ffe</testSuiteGuid>
   <testCaseLink>
      <guid>c5331dc5-e72a-48a3-aa21-245663e7623c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/wiki media</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4107db8d-92ba-4387-add4-1d5e74783d23</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/wiki/wiki-posgress</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>4107db8d-92ba-4387-add4-1d5e74783d23</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>city</value>
         <variableId>a0c7be27-9d44-4f72-a1b4-a97b51739607</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4107db8d-92ba-4387-add4-1d5e74783d23</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>result</value>
         <variableId>339f3bb2-5796-43a3-94f3-d02b744b43ba</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
